# Generated by Django 3.2.4 on 2021-06-10 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DysclozurUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=300, null=True)),
                ('avatar', models.CharField(max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(null=True)),
                ('link', models.URLField(null=True)),
                ('url_pic', models.URLField(null=True)),
                ('url_video', models.URLField(null=True)),
                ('upload_pic', models.ImageField(null=True, upload_to='images/')),
                ('upload_video', models.FileField(null=True, upload_to='videos/')),
                ('flairs', models.ManyToManyField(related_name='posts', to='dysclozur_api.Flair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysclozur_api.dysclozuruser')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysclozur_api.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysclozur_api.dysclozuruser')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysclozur_api.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dysclozur_api.dysclozuruser')),
            ],
        ),
    ]
