# Generated by Django 3.2.4 on 2021-06-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysclozur_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
