# Generated by Django 3.2.4 on 2021-06-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysclozur_api', '0002_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_pic',
            field=models.ImageField(null=True, upload_to='dysclozurImages'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_video',
            field=models.FileField(null=True, upload_to='dysclozurVideos'),
        ),
    ]
