# Generated by Django 3.2.4 on 2021-06-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysclozur_api', '0003_auto_20210621_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_pic',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
