# Generated by Django 3.2.4 on 2021-06-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysclozur_api', '0004_auto_20210621_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_video',
            field=models.URLField(null=True),
        ),
    ]
