# Generated by Django 3.2.4 on 2021-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dysclozur_api', '0005_alter_post_upload_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_video',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
